global:
  scrape_interval: 3s
  evaluation_interval: 3s

  external_labels:
    monitor: 'traefik'

rule_files:
  # - "first.rules"
  # - "second.rules"
  #
scrape_configs:
- job_name: 'node'
  static_configs:
    - targets: ['traefik:8080','localhost:9090','wallet.localhost:80']
